add_newline = false

scan_timeout = 10

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = "🌱 "
truncation_length = 20
truncation_symbol = ""

[package]
disabled = true

[cmd_duration]
prefix = ""

[nodejs]
symbol = "⬢  node "
style = "bold #43853d"
